### ISSUE TITLE
average commercial root weight (acrw)

### ISSUE THREAD

**Issue by rtbbase-helper** [Planteome/ibp-sweetpotato-traits#51]
## Submitter

|             |                     |
| ----------- | ------------------- |
| **Name**    | Jolien Swanckaert    |
| **Program** | CIP Ghana |

## Request

|                        |                           |
| ---------------------- | ------------------------- |
| **Trait Name**         | average commercial root weight (acrw)    |
| **Definition**         | average commercial root weight, commercial root weight divided by number of commercial roots     |
| **Trait Class**        | Agronomic   |
| **Measurement Method** | calculation        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | kg           |

**Comment by bellerbrock** [comment]
Hey Jolien, thanks for documenting all of these. It looks like this particular trait exists, but in a [confused form](https://github.com/Planteome/ibp-sweetpotato-traits/blob/master/sweetpotato_trait.obo#L3991).  The name is incorrect and both the synonym and the scale use incorrect units. 

Unfortunately because of the confusing name there is already data loaded for the trait, but it looks like its measures of the total commercial root weight not the average of individual commercial roots. We'll have to fix the problems with the trait here, and curate the measurements in sweetpotatobase that are linked to this trait but should probably be linked to https://sweetpotatobase.org/cvterm/77236/view

**Comment by jswancka** [comment]
Hi, good to hear from you.
We want to be optimistic and put it in kg. I think this is how HIDAP
calculates it.
Raul can you confirm?

Regards,
Jolien

**Comment by bellerbrock** [comment]
@jswancka Ah, I see. The synonym (RtACRW_Cp_g) suggested grams but the formula (ACRW = CRW / NOCR) definitely implies kg. I'll make it kg and it can be modified later if @reyzaguirre requests grams.

Also, I just updated the marketable yield values in sweetpotatobase so they all link to the correct trait (CO_331:0000809 'Storage root total marketable yield weight computation tons per ha'). The only remaining thing you may want to do is remove the old trait CO_331:0000680 'Storage root marketable yield weight computation tons per ha' from any lists you use

**Comment by jswancka** [comment]
I don’t feel strongly about this.  If Jolien thinks it should be kg, that is fine.

Ted

From: Jolien Swanckaert <swanckaertjolien@gmail.com>
Date: Thursday, 17 May 2018 at 21:27
To: Planteome/ibp-sweetpotato-traits <reply@reply.github.com>, Ted Carey <E.Carey@cgiar.org>, Raul Eyzaguirre <R.Eyzaguirre@cgiar.org>
Cc: Planteome/ibp-sweetpotato-traits <ibp-sweetpotato-traits@noreply.github.com>, Mention <mention@noreply.github.com>
Subject: Re: [Planteome/ibp-sweetpotato-traits] average commercial root weight (acrw) (#51)

Hi, good to hear from you.
We want to be optimistic and put it in kg. I think this is how HIDAP calculates it.
Raul can you confirm?

Regards,
Jolien

On Thu, May 17, 2018 at 7:21 PM, Bryan Ellerbrock <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey @jswancka<https://github.com/jswancka>, I'm working on this now. Do you have a preference for units in grams or kilograms? I'm guessing that the average weights will generally be under 1kg so that grams will make more sense?

**Comment by jswancka** [comment]
Yes, this is in kilograms.

**Comment by jswancka** [comment]
@bellerbrock Do we have any updates on these requests? I see that the trait average commercial root weight is no longer in the trait list in SPbase.
